# Generated by Django 3.0.8 on 2020-07-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageFile',
        ),
        migrations.AddField(
            model_name='user',
            name='imageFilelocation',
            field=models.CharField(default='ok', max_length=328),
        ),
    ]
