# Generated by Django 3.0.8 on 2020-07-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200723_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageFilelocation',
            field=models.CharField(max_length=328),
        ),
    ]
